// -*- c++ -*-
// Generated by gmmproc 2.44.0 -- DO NOT MODIFY!
#ifndef _GTKMM_APPLICATION_P_H
#define _GTKMM_APPLICATION_P_H


#include <giomm/private/application_p.h>

#include <glibmm/class.h>

namespace Gtk
{

class Application_Class : public Glib::Class
{
public:
#ifndef DOXYGEN_SHOULD_SKIP_THIS
  typedef Application CppObjectType;
  typedef GtkApplication BaseObjectType;
  typedef GtkApplicationClass BaseClassType;
  typedef Gio::Application_Class CppClassParent;
  typedef GApplicationClass BaseClassParent;

  friend class Application;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */

  const Glib::Class& init();


  static void class_init_function(void* g_class, void* class_data);

  static Glib::ObjectBase* wrap_new(GObject*);

protected:

  //Callbacks (default signal handlers):
  //These will call the *_impl member methods, which will then call the existing default signal callbacks, if any.
  //You could prevent the original default signal handlers being called by overriding the *_impl method.
  static void window_added_callback(GtkApplication* self, GtkWindow* p0);
  static void window_removed_callback(GtkApplication* self, GtkWindow* p0);

  //Callbacks (virtual functions):
};


} // namespace Gtk


#endif /* _GTKMM_APPLICATION_P_H */

