// -*- c++ -*-
// Generated by gmmproc 2.44.0 -- DO NOT MODIFY!
#ifndef _GTKMM_ICONSOURCE_P_H
#define _GTKMM_ICONSOURCE_P_H
#ifndef GTKMM_DISABLE_DEPRECATED


#endif // GTKMM_DISABLE_DEPRECATED


#endif /* _GTKMM_ICONSOURCE_P_H */

